site_name: Range Node Core
site_url: https://mataii.github.io/Range-Node-Core-Docs/

theme:
  name: material

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        es:
          name: Español
          build: true

docs_dir: docs
